### ISSUE TITLE
Detect duplicates

### ISSUE THREAD

**Issue by hola-soy-milk** [SaraVieira/retromatch#14]
I was thinking of having a toggle button. What do you think? 

<img width="1112" alt="Screenshot of hypothetical button" src="https://github.com/SaraVieira/retromatch/assets/656318/86a5a11f-edd8-4b52-b0e3-bb1a20e74da2">

**Comment by SaraVieira** [comment]
Yes!!

**Comment by hola-soy-milk** [comment]
Cool! I'll get on it. I wonder if it should delete duplicate files too 🤔 I'm leaning on yes

**Comment by hola-soy-milk** [comment]
Like not automatically, but offer

**Comment by hola-soy-milk** [comment]
Sweet! I'll get on this

**Comment by hola-soy-milk** [comment]
Upon further thought, I think a "clean up duplicates" wizard kinda thingy where it shows you both filenames and offers to keep one is better than toggling showing the duplicates. What do you think?

**Comment by SaraVieira** [comment]
Sure! Sounds like more work tho, that cool?

**Comment by hola-soy-milk** [comment]
Totally cool! What I'll probably do is split this in two PRs
