### ISSUE TITLE
Feature: Create a backlog page 

### ISSUE THREAD

**Issue by SaraVieira** [SaraVieira/retromatch#23]
Create a page where you can add games to your backlog 

This will use data from howlongtobeat and the page should have 

- A way to add and delete games 
- A list of games that can be moved up and down the list 
- How long each games takes to finish
- A total Time to finish all games

**Comment by hola-soy-milk** [comment]
Ooh this can be closed too, right?

**Comment by SaraVieira** [comment]
Oh yes
