### ISSUE TITLE
Backlog improvements

### ISSUE THREAD

**Issue by SaraVieira** [SaraVieira/retromatch#40]
- be able to order the games 
- clear text when adding a game

**Comment by hola-soy-milk** [comment]
Gonna take care of these! I love the backlog btw

**Comment by SaraVieira** [comment]
It's great right??

**Comment by hola-soy-milk** [comment]
Yes! I've started using it already :D

**Comment by hola-soy-milk** [comment]
Ok it seems the sorting is mostly working except for the release date formatting
